name: 'Configure the runtimes build'
description: 'Match strings against paths in diff for origin/main and current SHA'

inputs:
  configuration:
    description: 'the configuration to build'
    required: true
  cxx:
    description: 'C++ compiler'
    required: true
  cc:
    description: 'C compiler'
    required: true
  enable_clang_tidy:
    description: 'enable clang-tidy'
    required: false
    default: 'OFF'
  std_modules:
    description: 'enable std modules'
    required: false
    default: 'OFF'


runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
    - name: ${{ inputs.config }}.${{ inputs.cxx }}
      run: libcxx/utils/ci/run-buildbot ${{ matrix.config }}
      env:
        CC: ${{ inputs.cc }}
        CXX: ${{ inputs.cxx }}
        ENABLE_CLANG_TIDY: ${{ inputs.clang_tidy }}
        ENABLE_STD_MODULES: ${{ inputs.std_modules }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ inputs.config }}-${{ matrix.cxx }}-results
        path: |
          **/test-results.xml
          **/*.abilist
          **/CMakeError.log
          **/CMakeOutput.log
          **/crash_diagnostics/*
