name: 'Build LLVM Runtimes'
description: 'Configure and build the LLVM runtime libraries from source.'
author: 'eric@efcs.ca'
inputs:
  runtime:
    description: 'The runtime to test'
    required: True
    default: ''
  build:
    description: 'The build directory to target'
    required: false
    default: 'debug'
  name:
    description: 'The name used to identify this test suite run'
    required: False
    default: ''
  options:
    description: 'A list of LIT options to pass when running the tests'
    required: False
    default: ''
outputs:
  results:
    description: 'The path containing the xunit results'
runs:
  using: 'node12'
  main: 'dist/index.js'

