name: Test Dispatch Event

on: push

jobs:
  test-push:
    runs-on: [libcxx-builder]
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'actions'
      - uses: ./actions/dispatch-event
        with:
          repository: libcxx/actions
          token: ${{ secrets.personal_token }}
          event_type: 'test_event'
          client_payload: |
            {
              "foo": "bar"
            }
      - name: "other"
        run: |
          echo "HERE WE GO"



