#!/usr/bin/env bash

.set -eo pipefail

name=$1

if [[ -z "$name" ]]; then
  >&2 echo "Usage: npm run new-package [name]"
  exit 1
fi

lerna create @libcxx/$name
cat >packages/$name/tsconfig.json <<EOL
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./lib",
    "rootDir": "./src"
  },
  "include": [
    "./src"
  ]
}
EOL
