name: Trigger Build

on: push

jobs:
  debug:
    runs-on: [libcxx-builder]
    steps:
    - uses: libcxx/actions/dispatch@master
      with:
        event_type: build_request
        repository: libcxx/actions
        token: ${{ secrets.personal_token }}
        client_payload: |
          {
            "repository": "efcs/llvm-project",
            "ref": "broken-branch"
          }



