name: Build Runtimes

on: repository_dispatch
  types: [build_request]

jobs:
  debug:
    runs-on: [libcxx-builder]
    steps:
    - name: "Show Workspace"
      run: |
        ls -lart
        pwd
        ls
    - uses: actions/checkout@v2
      with:
        path: all-actions
    - uses: ./all-actions/build


