name: Build Runtimes

on: push

jobs:
  debug:
    runs-on: [libcxx-builder]
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.personal_token }}
    - name: "move actions"
      run: |
        git config --list --show-origin 1>&2
        mkdir actions/
        ls | grep -v actions | grep -v gitconfig | xargs mv -t actions/
    - uses: ./actions/build
    - uses: ./actions/test
      with:
        runtimes: 'libcxxabi libunwind'
    - uses: ./actions/publish
      with:
        publisher_key: ${{ secrets.publisher_key }}


