name: Build Runtimes

on:
  repository_dispatch:
    types: [build_request]


jobs:
  debug:
    runs-on: [libcxx-builder]
    steps:
    - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
    - uses: libcxx/actions/build@v0
      with:
        repository: ${{ github.event.client_payload.repository }}
        ref: ${{ github.event.client_payload.ref }}
        args: |
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
    - uses: libcxx/actions/test@v0
      with:
        id: 'libcxxabi'
        projects: |
          libcxxabi
    - uses: libcxx/actions/test@v0
      with:
        id: 'modules'
        args: |
          --param=enable_modules=true
    - uses: libcxx/actions/test@v0
      with:
        id: 'cxx03'
        args: |
          '--param=std=c++03'
        projects: |
          libcxx


