
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: libcxx-runners-small
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - run: echo "::error file=target.cpp,line=4,col=1::This is the first error"
      - run: python python-echo.py
      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: "artifact"
          path: out.xml
