name: Build Runtimes

on:
  repository_dispatch:
    types: [build_request]


jobs:
  debug:
    runs-on: [libcxx-builder]
    steps:
    - name: "Show Workspace"
      run: |
        ls -lart
        pwd
        ls
    - uses: actions/checkout@v2
      with:
        path: all-actions
    - uses: ./all-actions/build
      with:
        args: |
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
    - uses: ./all-actions/test
      with:
        id: 'libcxxabi'
        projects: |
          libcxxabi
    - uses: ./all-actions/test
      with:
        id: 'modules'
        args: |
          --param=enable_modules=true
    - uses: ./all-actions/test
      with:
        id: 'cxx03'
        args: |
          '--param=std=c++03'
        projects: |
          libcxx


