name: breathing test

on: push

jobs:
  basic_test:
    runs-on: [ubuntu-latest]
    steps:
    - name: "Checkout locally"
      uses: actions/checkout@v2
      with:
        path: '../actions'
    - name: 'Print Context'
      run: |
        echo $(ls)
        echo $(pwd)
    - name: "Test setup breathing"
      uses: ./../actions/setup
      with:
        name: 'breathing'
    - name: 'Print New Context'
      run: |
        echo $(ls)
        echo $(pwd)


