name: Build Runtimes

on: push

jobs:
  debug:
    runs-on: [libcxx-builder]
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'libcxx-actions'
    - uses: ./libcxx-actions/setup
      with:
        name: 'debug'
    - uses: ./libcxx-actions/test-runtimes
      with:
        runtime: 'libcxxabi'
    - uses: ./libcxx-actions/test-runtimes
      with:
        runtime: 'libcxx'


